name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'

jobs:
  backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PM2 globally
        run: |
          npm install -g pm2

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      # Optional: If you have a build step (like TypeScript)
      # - name: Build Project
      #   run: |
      #     cd Backend
      #     npm run build

      - name: Restart Backend with PM2
        run: |
          cd Backend
          pm2 delete backend || true
          pm2 start index.js --name backend
          pm2 save
